### ISSUE TITLE
books

### ISSUE THREAD

**Issue by Supriya-uchinthala123** [Supriya-uchinthala123/uber#17]
books branch

**Comment by bitrapravallika** [comment]
Introduction to Android Course Project: Book Shopping

Project Description: amazon one of the biggest Giants of E-Commerce in the Country is looking for Professionals so that they can develop an Android App of their website. Although this Application will only be dealing with the books category but if your App meets their expectations, they will also include other categories in it. 
The required books are been sold through amazon.
